using System.ComponentModel.DataAnnotations;
using SqliteRemoteApi.Models;
using SqliteRemoteApi.Models.Base;

namespace SqliteRemoteApi.Dto.Error;

#pragma warning disable CS8618 // Non-nullable field must contain a non-null value when exiting constructor. Consider adding the 'required' modifier or declaring as nullable.
public class DatabaseErrorResponseDto
{
  [Required]
  public string Type { get; init; }

  /// <summary>
  /// A short, human-readable summary of the problem type. It SHOULD NOT change from occurrence to occurrence
  /// of the problem, except for purposes of localization(e.g., using proactive content negotiation;
  /// see[RFC7231], Section 3.4).
  /// </summary>
  [Required]
  public string Title { get; init; }

  /// <summary>
  /// The HTTP status code([RFC7231], Section 6) generated by the origin server for this occurrence of the problem.
  /// </summary>
  [Required]
  public int Status { get; init; }

  /// <summary>
  /// A machine-readable explanation specific to this occurrence of the problem.
  /// </summary>
  [Required]
  public DatabaseOperationError Detail { get; init; }

  /// <summary>
  /// A URI reference that identifies the specific occurrence of the problem. It may or may not yield further information if dereferenced.
  /// </summary>
  [Required]
  public string Instance { get; init; }
  
  /// <summary>
  /// Extension to <see cref="Detail"/>. Provides a human-readable explanation specific to this occurrence of the problem.
  /// </summary>
  public string DetailContext { get; init; }
  
  /// <summary>
  /// Provides information about the remote host involved in the error.
  /// </summary>
  public DatabaseOperationSshHostDto? SshHost { get; init; }
}
#pragma warning restore CS8618 // Non-nullable field must contain a non-null value when exiting constructor. Consider adding the 'required' modifier or declaring as nullable.
