using System.ComponentModel.DataAnnotations;
using SqliteRemoteApi.Models.Base;

namespace SqliteRemoteApi.Dto.Error;

public class DatabaseErrorResponseDto
{
  [Required]
  public string Type { get; set; }

  /// <summary>
  /// A short, human-readable summary of the problem type. It SHOULD NOT change from occurrence to occurrence
  /// of the problem, except for purposes of localization(e.g., using proactive content negotiation;
  /// see[RFC7231], Section 3.4).
  /// </summary>
  [Required]
  public string Title { get; set; }

  /// <summary>
  /// The HTTP status code([RFC7231], Section 6) generated by the origin server for this occurrence of the problem.
  /// </summary>
  [Required]
  public int Status { get; set; }

  /// <summary>
  /// A human-readable explanation specific to this occurrence of the problem.
  /// </summary>
  [Required]
  public DatabaseOperationError Detail { get; set; }

  /// <summary>
  /// A URI reference that identifies the specific occurrence of the problem. It may or may not yield further information if dereferenced.
  /// </summary>
  [Required]
  public string Instance { get; set; }
}